md_front_addr = "tcp://180.168.146.187:10131"
trader_front_addr = "tcp://180.168.146.187:10130"
broker_id = "9999"
investor_id = "229073"
password = "admin@123456"
app_id = "simnow_client_test"
auth_code = "0000000000000000"
flow_path = "./ctp_flow/simnow/"
md_dynlib_path = "../lib/macos/6.7.7/cepin/thostmduserapi_se.framework/thostmduserapi_se"
td_dynlib_path = "../lib/macos/6.7.7/cepin/thosttraderapi_se.framework/thosttraderapi_se"
timeout_secs = 30
reconnect_interval_secs = 5
max_reconnect_attempts = 3

[environment]
env_type = "simnow"
simulation_mode = true

[logging]
level = "debug"
file_path = "./logs/ctp_simnow.log"
console = true
