[package]
name = "ctp-macos-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ctp2rs = { version = "0.1", features = ["ctp_v6_7_7"] }
clap = { version = "4", features = ["derive", "env"] }
chrono = "0.4"
