# 生产环境配置文件
# 警告：这是生产环境配置，请谨慎修改！

[ctp]
environment = "production"
# 行情前置地址（请替换为实际的生产环境地址）
md_front_addr = "tcp://your-production-md-server:port"
# 交易前置地址（请替换为实际的生产环境地址）
trader_front_addr = "tcp://your-production-trader-server:port"
# 经纪商代码（请填写实际的经纪商代码）
broker_id = ""
# 投资者代码（请填写您的生产账号）
investor_id = ""
# 密码（请填写您的生产密码）
password = ""
# 应用标识（请填写实际的应用标识）
app_id = ""
# 授权编码（请填写实际的授权编码）
auth_code = ""
# 流文件路径
flow_path = "./ctp_flow/production/"
# 超时时间（秒）
timeout_secs = 30
# 重连间隔（秒）
reconnect_interval_secs = 5
# 最大重连次数
max_reconnect_attempts = 3

[logging]
# 日志级别: trace, debug, info, warn, error
level = "warn"
# 日志文件路径
file_path = "./logs/ctp_production.log"
# 是否在控制台输出日志（生产环境建议关闭）
console = false

[environment]
# 环境类型
env_type = "production"
# 是否启用模拟模式（生产环境必须为 false）
simulation_mode = false