# TTS 7x24 测试环境配置文件
# 这是一个示例配置，请根据实际情况修改

[ctp]
environment = "tts"
# 行情前置地址
md_front_addr = "tcp://121.37.80.177:20004"
# 交易前置地址
trader_front_addr = "tcp://121.37.80.177:20002"
# 经纪商代码
broker_id = "9999"
# 投资者代码（请填写您的账号）
investor_id = ""
# 密码（请填写您的密码）
password = ""
# 应用标识
app_id = "simnow_client_test"
# 授权编码
auth_code = "0000000000000000"
# 流文件路径
flow_path = "./ctp_flow/tts/"
# 超时时间（秒）
timeout_secs = 30
# 重连间隔（秒）
reconnect_interval_secs = 5
# 最大重连次数
max_reconnect_attempts = 3

[logging]
# 日志级别: trace, debug, info, warn, error
level = "info"
# 日志文件路径
file_path = "./logs/ctp_tts.log"
# 是否在控制台输出日志
console = true

[environment]
# 环境类型
env_type = "tts"
# 是否启用模拟模式
simulation_mode = true